# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maverick/Documents/Proyecto/C++/EncryptorProyect

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maverick/Documents/Proyecto/C++/EncryptorProyect

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maverick/Documents/Proyecto/C++/EncryptorProyect/CMakeFiles /home/maverick/Documents/Proyecto/C++/EncryptorProyect//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maverick/Documents/Proyecto/C++/EncryptorProyect/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named encryptor

# Build rule for target.
encryptor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 encryptor
.PHONY : encryptor

# fast build rule for target.
encryptor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/build
.PHONY : encryptor/fast

src/colors.o: src/colors.cpp.o
.PHONY : src/colors.o

# target to build an object file
src/colors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/colors.cpp.o
.PHONY : src/colors.cpp.o

src/colors.i: src/colors.cpp.i
.PHONY : src/colors.i

# target to preprocess a source file
src/colors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/colors.cpp.i
.PHONY : src/colors.cpp.i

src/colors.s: src/colors.cpp.s
.PHONY : src/colors.s

# target to generate assembly for a file
src/colors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/colors.cpp.s
.PHONY : src/colors.cpp.s

src/directories.o: src/directories.cpp.o
.PHONY : src/directories.o

# target to build an object file
src/directories.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/directories.cpp.o
.PHONY : src/directories.cpp.o

src/directories.i: src/directories.cpp.i
.PHONY : src/directories.i

# target to preprocess a source file
src/directories.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/directories.cpp.i
.PHONY : src/directories.cpp.i

src/directories.s: src/directories.cpp.s
.PHONY : src/directories.s

# target to generate assembly for a file
src/directories.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/directories.cpp.s
.PHONY : src/directories.cpp.s

src/encryption.o: src/encryption.cpp.o
.PHONY : src/encryption.o

# target to build an object file
src/encryption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/encryption.cpp.o
.PHONY : src/encryption.cpp.o

src/encryption.i: src/encryption.cpp.i
.PHONY : src/encryption.i

# target to preprocess a source file
src/encryption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/encryption.cpp.i
.PHONY : src/encryption.cpp.i

src/encryption.s: src/encryption.cpp.s
.PHONY : src/encryption.s

# target to generate assembly for a file
src/encryption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/encryption.cpp.s
.PHONY : src/encryption.cpp.s

src/file_utils.o: src/file_utils.cpp.o
.PHONY : src/file_utils.o

# target to build an object file
src/file_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/file_utils.cpp.o
.PHONY : src/file_utils.cpp.o

src/file_utils.i: src/file_utils.cpp.i
.PHONY : src/file_utils.i

# target to preprocess a source file
src/file_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/file_utils.cpp.i
.PHONY : src/file_utils.cpp.i

src/file_utils.s: src/file_utils.cpp.s
.PHONY : src/file_utils.s

# target to generate assembly for a file
src/file_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/file_utils.cpp.s
.PHONY : src/file_utils.cpp.s

src/key_derivation.o: src/key_derivation.cpp.o
.PHONY : src/key_derivation.o

# target to build an object file
src/key_derivation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/key_derivation.cpp.o
.PHONY : src/key_derivation.cpp.o

src/key_derivation.i: src/key_derivation.cpp.i
.PHONY : src/key_derivation.i

# target to preprocess a source file
src/key_derivation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/key_derivation.cpp.i
.PHONY : src/key_derivation.cpp.i

src/key_derivation.s: src/key_derivation.cpp.s
.PHONY : src/key_derivation.s

# target to generate assembly for a file
src/key_derivation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/key_derivation.cpp.s
.PHONY : src/key_derivation.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu.o: src/menu.cpp.o
.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i
.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s
.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/mysql_utils.o: src/mysql_utils.cpp.o
.PHONY : src/mysql_utils.o

# target to build an object file
src/mysql_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/mysql_utils.cpp.o
.PHONY : src/mysql_utils.cpp.o

src/mysql_utils.i: src/mysql_utils.cpp.i
.PHONY : src/mysql_utils.i

# target to preprocess a source file
src/mysql_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/mysql_utils.cpp.i
.PHONY : src/mysql_utils.cpp.i

src/mysql_utils.s: src/mysql_utils.cpp.s
.PHONY : src/mysql_utils.s

# target to generate assembly for a file
src/mysql_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/mysql_utils.cpp.s
.PHONY : src/mysql_utils.cpp.s

src/openssl_utils.o: src/openssl_utils.cpp.o
.PHONY : src/openssl_utils.o

# target to build an object file
src/openssl_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/openssl_utils.cpp.o
.PHONY : src/openssl_utils.cpp.o

src/openssl_utils.i: src/openssl_utils.cpp.i
.PHONY : src/openssl_utils.i

# target to preprocess a source file
src/openssl_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/openssl_utils.cpp.i
.PHONY : src/openssl_utils.cpp.i

src/openssl_utils.s: src/openssl_utils.cpp.s
.PHONY : src/openssl_utils.s

# target to generate assembly for a file
src/openssl_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/openssl_utils.cpp.s
.PHONY : src/openssl_utils.cpp.s

src/password_prompt.o: src/password_prompt.cpp.o
.PHONY : src/password_prompt.o

# target to build an object file
src/password_prompt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/password_prompt.cpp.o
.PHONY : src/password_prompt.cpp.o

src/password_prompt.i: src/password_prompt.cpp.i
.PHONY : src/password_prompt.i

# target to preprocess a source file
src/password_prompt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/password_prompt.cpp.i
.PHONY : src/password_prompt.cpp.i

src/password_prompt.s: src/password_prompt.cpp.s
.PHONY : src/password_prompt.s

# target to generate assembly for a file
src/password_prompt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/password_prompt.cpp.s
.PHONY : src/password_prompt.cpp.s

src/time_utils.o: src/time_utils.cpp.o
.PHONY : src/time_utils.o

# target to build an object file
src/time_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/time_utils.cpp.o
.PHONY : src/time_utils.cpp.o

src/time_utils.i: src/time_utils.cpp.i
.PHONY : src/time_utils.i

# target to preprocess a source file
src/time_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/time_utils.cpp.i
.PHONY : src/time_utils.cpp.i

src/time_utils.s: src/time_utils.cpp.s
.PHONY : src/time_utils.s

# target to generate assembly for a file
src/time_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/encryptor.dir/build.make CMakeFiles/encryptor.dir/src/time_utils.cpp.s
.PHONY : src/time_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... encryptor"
	@echo "... src/colors.o"
	@echo "... src/colors.i"
	@echo "... src/colors.s"
	@echo "... src/directories.o"
	@echo "... src/directories.i"
	@echo "... src/directories.s"
	@echo "... src/encryption.o"
	@echo "... src/encryption.i"
	@echo "... src/encryption.s"
	@echo "... src/file_utils.o"
	@echo "... src/file_utils.i"
	@echo "... src/file_utils.s"
	@echo "... src/key_derivation.o"
	@echo "... src/key_derivation.i"
	@echo "... src/key_derivation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/mysql_utils.o"
	@echo "... src/mysql_utils.i"
	@echo "... src/mysql_utils.s"
	@echo "... src/openssl_utils.o"
	@echo "... src/openssl_utils.i"
	@echo "... src/openssl_utils.s"
	@echo "... src/password_prompt.o"
	@echo "... src/password_prompt.i"
	@echo "... src/password_prompt.s"
	@echo "... src/time_utils.o"
	@echo "... src/time_utils.i"
	@echo "... src/time_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

